
  name: Build, Test, and Deploy with Docker Compose

  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

  jobs:  
    deploy:
      runs-on: ubuntu-latest
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      steps:
        - name: Deploy to production server
          run: |
            sshpass -p '${{ secrets.SSH_PASSWORD }}' ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} \
            "cd action_vps && git pull && docker compose up -d"
          env:
            SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}